name: RoguelikeSpigot
version: '${project.version}'
main: me.jofri.roguelikespigot.RoguelikeSpigot
api-version: '1.20'
commands:
  generatedungeon:
    description: Generates a dungeon
    usage: /<command>
  cleardungeon:
    description: clears the dungeon
    usage: /<command>
